baseurl = "https://www.silkage.net/"
languageCode = "zh-cn"
title = "锦年安好"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "icarus"
# Comment the themesDir option if you use this theme in production
themesDir = "./themes"


[permalinks]
    # post = "/:year/:month/:day/:slug"
    post = "/:year/:month/:day/:filename/"

[params]
    # Tell me who you are
    author = "Silkage"
    bio = "我的愿望是世界和平"
    location = "四川.成都"
    site_description = "在这里我会向大家分享软件编程与日常开发的经验与读书心得和笔记，同时也会记录工作与生活中的点点滴滴，欢迎大家持续关注与订阅。"
    copyright  = "Silkage [蜀ICP备16030664号-2](http://beian.miit.gov.cn)"
    avatar = "css/images/avatar.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = "935411557@qq.com"
    logo = "css/images/logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

      # algolia site search
    algolia_search = true
    algolia_appId = "CXEO51HCGP"
    algolia_indexName = "blog"
    algolia_apiKey = "9ea1ca1288e5b645ba4e8b561d06ce49"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "首页"
    link   = "/"

[[params.menu]]
    before = true
    label = "归档"
    link = "archives/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/SilkageNet"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "SilkageNet"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "silkage"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = true
    tags = true
    tag_cloud = true

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]